export default {
  REHYDRATE: 'persist/REHYDRATE',
  AUTH_SIGN_UP_REQUEST: '@auth/SIGN_UP_REQUEST',
  AUTH_SIGN_UP_SUCCESS: '@auth/SIGN_UP_SUCCESS',
  AUTH_SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
  AUTH_SIGN_FAILURE: '@auth/SIGN_FAILURE',
  AUTH_SIGN_OUT: '@auth/SIGN_OUT',
  USER_PROFILE_UPDATE_REQUEST: '@user/UPDATE_PROFILE_REQUEST',
  USER_PROFILE_UPDATE_SUCCESS: '@user/UPDATE_PROFILE_SUCCESS',
  USER_PROFILE_UPDATE_FAILURE: '@user/UPDATE_PROFILE_FAILURE',
};
